"""add a column

Revision ID: 45b2b2f718b6
Revises: 646f724d856f
Create Date: 2022-09-19 12:38:42.169753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45b2b2f718b6'
down_revision = '646f724d856f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'type_of_recipe',
               existing_type=postgresql.ENUM('salat', 'pervoe', 'vtoroe', 'desert', 'napitok', 'vipechka', name='typerecipeenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'type_of_recipe',
               existing_type=postgresql.ENUM('salat', 'pervoe', 'vtoroe', 'desert', 'napitok', 'vipechka', name='typerecipeenum'),
               nullable=True)
    # ### end Alembic commands ###
