"""add a column

Revision ID: 4aff92bf5e12
Revises: 45b2b2f718b6
Create Date: 2022-09-19 14:46:22.601766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4aff92bf5e12'
down_revision = '45b2b2f718b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Название типа блюда'),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=True)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.add_column('recipes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'categories', ['category_id'], ['id'])
    op.drop_column('recipes', 'type_of_recipe')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('type_of_recipe', postgresql.ENUM('salat', 'pervoe', 'vtoroe', 'desert', 'napitok', 'vipechka', name='typerecipeenum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'category_id')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
