"""add a column

Revision ID: 646f724d856f
Revises: 9a0eb2673263
Create Date: 2022-09-19 12:25:47.320050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '646f724d856f'
down_revision = '9a0eb2673263'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'type_of_recipe',
               existing_type=postgresql.ENUM('salat', 'pervoe', 'vtoroe', 'desert', 'napitok', 'vipechka', name='typerecipeenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'type_of_recipe',
               existing_type=postgresql.ENUM('salat', 'pervoe', 'vtoroe', 'desert', 'napitok', 'vipechka', name='typerecipeenum'),
               nullable=False)
    # ### end Alembic commands ###
