"""New Migration

Revision ID: 7688c83b3582
Revises: 64ad69455dcc
Create Date: 2022-09-17 21:37:55.234143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7688c83b3582'
down_revision = '64ad69455dcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
