"""add a column

Revision ID: 9a0eb2673263
Revises: 7688c83b3582
Create Date: 2022-09-19 11:45:39.518069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0eb2673263'
down_revision = '7688c83b3582'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'users', ['author_id'], ['id'])
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'author_id')
    # ### end Alembic commands ###
