"""add a column

Revision ID: f8f685ee103e
Revises: 4aff92bf5e12
Create Date: 2022-09-19 15:53:15.450380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f685ee103e'
down_revision = '4aff92bf5e12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
